version: 2.0 # Permet de vérifier les modifications

permission_categories:
  
  - code: "ADMIN-1"
    label: "Gestion administration"
    permissions:
      - code: "perm.users.list"
        label: "Voir liste des utilisateurs"
      - code: "perm.roles.list"
        label: "Voir liste des roles"
      - code: "perm.eglises.list"
        label: "Voir liste des eglises"
      - code: "perm.membres.list"
        label: "Voir liste des membres"
      - code: "perm.persons.list"
        label: "Voir liste des personnes"
      - code: "perm.localites.list"
        label: "Voir liste des localites"
      - code: "perm.types.localites.list"
        label: "Voir liste des types de localites"
      - code: "perm.parametres.list"
        label: "Voir les parametrages"
      - code: "perm.credits.list"
        label: "Voir liste des credits"
        
  - code: "REFER-2"
    label: "Gestion des références"
    permissions:
      - code: "perm.country.list"
        label: "Voir liste des pays"
      - code: "perm.sexe.list"
        label: "Voir liste des sexes"
      - code: "perm.departement.list"
        label: "Voir liste des departements"
      - code: "perm.year.list"
        label: "Voir liste des annees"
      - code: "perm.var.list"
        label: "Voir liste des variables"
      - code: "perm.config.list"
        label: "Voir liste des configurations"
        
  - code: "PAIEM-3"
    label: "Gestion des paiements"
    permissions:
      - code: "perm.paie.list"
        label: "Voir liste des paiements"
      - code: "perm.promesse.list"
        label: "Voir liste des promesses"
menus:
  - code: "ADMINISTRATION"
    label: "Administration"
    items:
      - code: "admin.users.list"
        label: "Utilisateurs"
        path: "/paie/pages/admin/users/list"
        requiredPermission: "perm.users.list"
        icon: "fa-solid fa-users"
      - code: "admin.roles.list"
        label: "Rôles"
        path: "/paie/pages/admin/roles/list"
        requiredPermission: "perm.roles.list"
        icon: "fa-solid fa-ring"
      - code: "admin.entites.eglises.list"
        label: "Eglises"
        path: "/paie/pages/admin/entites/eglises/list"
        requiredPermission: "perm.eglises.list"
        icon: "fa-solid fa-synagogue"
        order: "3"
      - code: "admin.membres.list"
        label: "Membres"
        path: "/paie/pages/admin/members/list"
        requiredPermission: "perm.membres.list"
        icon: "fa-solid fa-users"
        order: "4"
        
  - code: "REFERENCE"
    label: "Références"
    items:
      - code: "admin.references.country.list"
        label: "Pays"
        path: "/paie/pages/admin/references/country/list"
        requiredPermission: "perm.country.list"
        icon: "fa-solid fa-globe"
        order: "1"
      - code: "admin.references.sexe.list"
        label: "Sexe"
        path: "/paie/pages/admin/references/sexe/list"
        requiredPermission: "perm.sexe.list"
        icon: "fa-solid fa-genderless"
        order: "2"
      - code: "admin.references.departement.list"
        label: "Départements"
        path: "/paie/pages/admin/references/department/list"
        requiredPermission: "perm.departement.list"
        icon: "fa-solid fa-users-viewfinder"
        order: "3"
      - code: "admin.reference.year.list"
        label: "Années"
        path: "/paie/pages/admin/references/annees/list"
        requiredPermission: "perm.year.list"
        icon: "fa-regular fa-calendar"
        order: "6"
      - code: "admin.references.var.list"
        label: "Variables"
        path: "/paie/pages/admin/references/variables/list"
        requiredPermission: "perm.var.list"
        icon: "pi pi-table"
        order: "4"
      - code: "admin.reference.config.list"
        label: "Configurations"
        path: "/paie/pages/admin/references/config/list"
        requiredPermission: "perm.config.list"
        icon: "pi pi-table"
        order: "5"
        
  - code: "PAYMENTS"
    label: "Paiements"
    items:
      - code: "admin.pay.payment"
        label: "Paiements"
        path: "/paie/pages/admin/pay/payment/list"
        requiredPermission: "perm.promesse.list"
        icon: "pi pi-sliders-h"
        order: "1"
      - code: "admin.pay.promised"
        label: "Promesses"
        path: "/paie/pages/admin/pay/promised/list"
        requiredPermission: "perm.promesse.list"
        icon: "pi pi-sliders-h"
        order: "2"