version: 1.0 # Permet de vérifier les modifications
permission_categories:
  - code: "ADMIN-1"
    label: "Gestion administration"
    permissions:
      - code: "perm.users.list"
        label: "Voir liste des utilisateurs"
      - code: "perm.roles.list"
        label: "Voir liste des roles"
      - code: "perm.eglises.list"
        label: "Voir liste des eglises"
      - code: "perm.membres.list"
        label: "Voir liste des membres"
      - code: "perm.persons.list"
        label: "Voir liste des personnes"
      - code: "perm.localites.list"
        label: "Voir liste des localites"
      - code: "perm.types.localites.list"
        label: "Voir liste des types de localites"
      - code: "perm.parametres.list"
        label: "Voir les parametrages"
      - code: "perm.credits.list"
        label: "Voir liste des credits"
  - code: "REFER-2"
    label: "Gestion des références"
    permissions:
      - code: "perm.pays.list"
        label: "Voir liste des pays"
      - code: "perm.sexes.list"
        label: "Voir liste des sexes"
      - code: "perm.departements.list"
        label: "Voir liste des departements"
      - code: "perm.annees.list"
        label: "Voir liste des annees"
      - code: "perm.var.list"
        label: "Voir liste des variables"
      - code: "perm.configs.list"
        label: "Voir liste des configurations"
  - code: "PAIEM-3"
    label: "Gestion des paiements"
    permissions:
      - code: "perm.paie.list"
        label: "Voir liste des paiements"
menus:
  - code: "ADMINISTRATION"
    label: "Administration"
    items:
      - code: "admin.users.list"
        label: "Utilisateurs"
        path: "/paie/pages/admin/users/list"
        requiredPermission: "perm.users.list"
        icon: "pi pi-users"
      - code: "admin.roles.list"
        label: "Rôles"
        path: "/paie/pages/admin/roles/list"
        requiredPermission: "perm.roles.list"
        icon: "pi pi-shield"
      - code: "admin.entites.eglises.list"
        label: "Eglises"
        path: "/paie/pages/admin/entites/eglises/list"
        requiredPermission: "perm.eglises.list"
        icon: "pi pi-home"
      - code: "admin.membres.list"
        label: "Membres"
        path: "/paie/pages/admin/membres/list"
        requiredPermission: "perm.membres.list"
        icon: "pi pi-sliders-h"
  - code: "REFERENCE"
    label: "Références"
    items:
      - code: "admin.reference.country"
        label: "Pays"
        path: "/paie/pages/admin/references/country/list"
        requiredPermission: "perm.pays.list"
        icon: "pi pi-sliders-h"
      - code: "admin.reference.var"
        label: "Variables"
        path: "/paieT/paie/pages/admin/references/variables/list"
        requiredPermission: "perm.var.list"
        icon: "pi pi-sliders-h"
  - code: "PAYMENTS"
    label: "Paiements"
    items:
      - code: "admin.pay.promised"
        label: "Paiements"
        path: "/paie/pages/admin/pay/promised/list"
        requiredPermission: "perm.paie.list"
        icon: "pi pi-sliders-h"