version: 2.0 # Permet de vérifier les modifications

permission_categories:

  - code: "ADMIN-1"
    label: "Gestion administration"
    # Permissions : Menu de Administration
    permissions:
      - code: "perm.users.list"
        label: "Voir liste des utilisateurs"
      - code: "perm.users.all"
        label: "Gerer les utilisteurs"
        
      - code: "perm.roles.list"
        label: "Voir liste des roles"
      - code: "perm.roles.all"
        label: "Gerer les roles"     
        
      - code: "perm.eglises.list"
        label: "Voir liste des eglises"
      - code: "perm.eglises.all"
        label: "Gerer les eglises"
        
      - code: "perm.membres.list"
        label: "Voir liste des membres"
      - code: "perm.membres.all"
        label: "Gerer les membres"
        
      - code: "perm.persons.list"
        label: "Voir liste des personnes"
      - code: "perm.persons.all"
        label: "Gerer les personnes"
        
      - code: "perm.localites.list"
        label: "Voir liste des localites"
      - code: "perm.localites.all"
        label: "Gerer les localites"
        
      - code: "perm.types.localites.all"
        label: "Gerer les type de localites"
      - code: "perm.types.localites.list"
        label: "Voir liste des types de localites"
        
      - code: "perm.params.list"
        label: "Voir les parametrages"
      - code: "perm.params.all"
        label: "Gerer les parametrages"
        
      - code: "perm.credits.list"
        label: "Voir liste des credits"
      - code: "perm.credits.all"
        label: "Gerer les credits"

     # Permissions : Menu de References
  - code: "REFER-2"
    label: "Gestion des références"
    permissions:
      - code: "perm.pays.list"
        label: "Voir liste des pays"
      - code: "perm.pays.all"
        label: "Gerer les pays"
        
      - code: "perm.sexes.list"
        label: "Voir liste des sexes"
      - code: "perm.sexes.all"
        label: "Gerer les sexes"
        
      - code: "perm.departements.list"
        label: "Voir liste des departements"
      - code: "perm.departements.all"
        label: "Gerer les departements"
        
      - code: "perm.years.list"
        label: "Voir liste des annees"
      - code: "perm.years.all"
        label: "Gerer les annees"
        
      - code: "perm.vars.list"
        label: "Voir liste des variables"
      - code: "perm.vars.all"
        label: "Gerer les vars"
        
      - code: "perm.configs.list"
        label: "Voir liste des configurations"
      - code: "perm.configs.all"
        label: "Gerer les configurations"

        # Permissions : Menu de Paiements
  - code: "PAIEM-3"
    label: "Gestion des paiements"
    permissions:
      - code: "perm.pay.list"
        label: "Voir liste des paiements"
      - code: "perm.pay.all"
        label: "Gerer les paiements"
        
      - code: "perm.promesse.list"
        label: "Voir liste des promesses"
      - code: "perm.promesse.all"
        label: "Gerer les promesses"
        
      - code: "perm.sum.paid.list"
        label: "Voir liste des sommes payes"
      - code: "perm.sum.paid.all"
        label: "Gerer les sommes payes"

        ##### Menus et Menus Items #####
menus:
  - code: "ADMINISTRATION"
    label: "Administration"
    items:
      - code: "admin.users.list"
        label: "Utilisateurs"
        path: "/paie/pages/admin/users/list"
        requiredPermission: "perm.users.list"
        icon: "fa-solid fa-users"
        order: "1"
      - code: "admin.roles.list"
        label: "Rôles"
        path: "/paie/pages/admin/roles/list"
        requiredPermission: "perm.roles.list"
        icon: "fa-solid fa-ring"
        order: "2"
      - code: "admin.entites.eglises.list"
        label: "Églises"
        path: "/paie/pages/admin/entites/eglises/list"
        requiredPermission: "perm.eglises.list"
        icon: "fa-solid fa-synagogue"
        order: "3"
      - code: "admin.membres.list"
        label: "Membres"
        path: "/paie/pages/admin/members/list"
        requiredPermission: "perm.membres.list"
        icon: "fa-solid fa-users"
        order: "4"
      - code: "admin.persons.list"
        label: "Personnes"
        path: "/paie/pages/admin/persons/list"
        requiredPermission: "perm.persons.list"
        icon: "fa-solid fa-user"
        order: "5"
      - code: "admin.localites.list"
        label: "Localités"
        path: "/paie/pages/admin/localities/locality/list"
        requiredPermission: "perm.localites.list"
        icon: "fa-solid fa-location-dot"
        order: "6"
      - code: "admin.types.localites.list"
        label: "Types de localités"
        path: "/paie/pages/admin/localities/type-locality/list"
        requiredPermission: "perm.types.localites.list"
        icon: "fa-solid fa-location-dot"
        order: "7"
      - code: "admin.params.list"
        label: "Paramètres"
        path: "/paie/pages/admin/params/list"
        requiredPermission: "perm.params.list"
        icon: "fa-solid fa-gear"
        order: "8"
      - code: "admin.credits.list"
        label: "Crédits"
        path: "/paie/pages/admin/loan/list"
        requiredPermission: "perm.credits.list"
        icon: "fa-solid fa-coins"
        order: "9"

  - code: "REFERENCE"
    label: "Références"
    items:
      - code: "reference.country.list"
        label: "Pays"
        path: "/paie/pages/admin/references/country/list"
        requiredPermission: "perm.pays.list"
        icon: "fa-solid fa-globe"
        order: "1"
      - code: "reference.sexe.list"
        label: "Sexe"
        path: "/paie/pages/admin/references/sexe/list"
        requiredPermission: "perm.sexes.list"
        icon: "fa-solid fa-genderless"
        order: "2"
      - code: "reference.departement.list"
        label: "Départements"
        path: "/paie/pages/admin/references/department/list"
        requiredPermission: "perm.departements.list"
        icon: "fa-solid fa-users-viewfinder"
        order: "3"
      - code: "reference.year.list"
        label: "Années"
        path: "/paie/pages/admin/references/annees/list"
        requiredPermission: "perm.years.list"
        icon: "fa-regular fa-calendar"
        order: "4"
      - code: "reference.var.list"
        label: "Variables"
        path: "/paie/pages/admin/references/variables/list"
        requiredPermission: "perm.vars.list"
        icon: "pi pi-table"
        order: "5"
      - code: "reference.config.list"
        label: "Configurations"
        path: "/paie/pages/admin/references/config/list"
        requiredPermission: "pi pi-envelope"
        icon: "pi pi-table"
        order: "6"
        
  - code: "PAYMENTS"
    label: "Paiements"
    items:
      - code: "pay.payment"
        label: "Promesses"
        path: "/paie/pages/admin/pay/payment/list"
        requiredPermission: "perm.promesse.list"
        icon: "fa-solid fa-handshake-slash"
        order: "1"
      - code: "pay.paiements"
        label: "Paiements"
        path: "/paie/pages/admin/pay/promised/list"
        requiredPermission: "perm.pay.list"
        icon: "fa-solid fa-money-bill-transfer"
        order: "3"
      - code: "pay.promised"
        label: "Sommes payés"
        path: "/paie/pages/admin/pay/sum-pay/list"
        requiredPermission: "perm.sum.paid.list"
        icon: "fa-solid fa-circle-dollar-to-slot"
        order: "2"