
# Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
# Click nbfs://nbhost/SystemFileSystem/Templates/Other/properties.properties to edit this template

project.stage=Development
datasource.jndiname=java:app/jdbc/paie
datasource.pool=paiePool
datasource.url=jdbc:postgresql://localhost:5432/paie
datasource.host=localhost
datasource.port=5432
datasource.dbname=paie
datasource.driver=org.postgresql.Driver
datasource.username= mediasoft
datasource.password= mediasoft
context.path=paie-web
persistence.schema=create
persitence.logging.parameters=true
persistence.logging.level.sql=FINE